dietas <- read.delim("~/Descargas/dietas.txt")
nombrecol <- colnames(dietas)
#a)
mediaA <- mean(dietas$dietaa)
mediaB <- mean(dietas$dietab)
mediaC <- mean(dietas$dietac)
medianaA <- median(dietas$dietaa)
medianaB <- median(dietas$dietab)
medianaC <- median(dietas$dietac)
mediaP1A <- mean(dietas$dietaa,trim=0.1)
mediaP1B <- mean(dietas$dietab,trim=0.1)
mediaP1C <- mean(dietas$dietac,trim=0.1)
mediaP2A <- mean(dietas$dietaa,trim=0.2)
mediaP2B <- mean(dietas$dietab,trim=0.2)
mediaP2C <- mean(dietas$dietac,trim=0.2)

#colmean(dietas) apply(dietas,2,FUN="median/mad...)

#b)
desvioStandarA <- sd(dietas$dietaa)
desvioStandarB <- sd(dietas$dietab)
desvioStandarC <- sd(dietas$dietac)
distInterqA <-  IQR(dietas$dietaa)
distInterqB <-  IQR(dietas$dietab)
distInterqC <-  IQR(dietas$dietac)
madA <- mad(dietas$dietaa,constant=1)
madB <- mad(dietas$dietab,constant=1)
madC <- mad(dietas$dietac,constant=1)
#c)
percentilesA <- quantile(dietas$dietaa, probs = c(0.1,0.25,0.5,0.75,0.9))
percentilesB <- quantile(dietas$dietab, probs = c(0.1,0.25,0.5,0.75,0.9))
percentilesC <- quantile(dietas$dietac, probs = c(0.1,0.25,0.5,0.75,0.9))
#d)
par(mfrow=c(1,3))
hist(dietas$dietaa, main="Histograma dieta A",col = "purple2",xlab="valores de glucosa")
hist(dietas$dietab, main="Histograma dieta B",col = "firebrick",xlab="valores de glucosa")
hist(dietas$dietac, main="Histograma dieta C",col = "salmon",xlab="valores de glucosa")
#e)
par(mfrow=c(3,1))
boxplot(dietas$dietaa, horizontal = TRUE, main="Boxplot dieta A",col ="pink")
boxplot(dietas$dietab, horizontal = TRUE, main="Boxplot dieta B",col ="cyan2")
boxplot(dietas$dietac, horizontal = TRUE, main="Boxplot dieta C",col ="violet")
#f)
par(mfrow=c(3,1))
qqnorm(dietas$dietaa, main="QQ-Plot dieta A")
qqline(dietas$dietaa)
qqnorm(dietas$dietab, main="QQ-Plot dieta B")
qqline(dietas$dietab)
qqnorm(dietas$dietac, main="QQ-Plot dieta C")
qqline(dietas$dietac)
